//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteorologyStationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int iddata { get; set; }
        public Nullable<decimal> tempreture { get; set; }
        public Nullable<decimal> humidity { get; set; }
        public Nullable<int> pressure { get; set; }
        public int iddevice { get; set; }
        public int idregion { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual devices devices { get; set; }
        public virtual regions regions { get; set; }
    }
}
